### ISSUE TITLE
Web App support

### ISSUE THREAD

**Issue by shakirpa** [CastawayLabs/dart-escpos#3]
Hello, Thanks a lot for the null safety implementation. 
It was bit difficult to find the package directly from the google search... stil managed to get it :)
Thanks a lot for the support

Could you please implement the POS Printer support for web app also ?

**Comment by matejkramny** [comment]
Hi, I don't think that's possible.

https://github.com/andrey-ushakov/esc_pos_printer/issues/71 - this highlights one issue, technically the Socket class is not available for the web platform. That's not really the problem IMO.

Fundamentally, you can't really open raw TCP connections in a browser environment. If browsers did support this, I imagine it'd be a massive security risk..
Anyway I did some quick research for this, see [here (although a little outdated)](https://stackoverflow.com/questions/60266060/how-can-i-use-sockets-with-flutter-web). The websocket answer is correct but it won't work with ESCPOS since they don't support the HTTP protocol.

Some escpos printers support printing APIs (that work over http) but that's out of scope for this library unless someone is willing to add that
