### ISSUE TITLE
General question to usage and changes

### ISSUE THREAD

**Issue by emmaxCreative** [CastawayLabs/dart-escpos#4]
Since I use https://github.com/andrey-ushakov/esc_pos_printer/ and this is a fork of it I wanna know if some of the bugs that are open since months in the other repo, are fixed in this library before changing my code. ?
Especially the bug where columns do not wrap long text to new line and therefore cutoff lots of relevant informations.

**Comment by matejkramny** [comment]
Hey @emmaxCreative, yes that one in particular is fixed since we rolled back to an earlier version which did not cause column wrapping issues

The changes are more or less outlined in [CHANGELOG.md](https://github.com/CastawayLabs/dart-escpos/blob/master/CHANGELOG.md), as well as null safety, rollback to a working version and merging the utils project

**Comment by emmaxCreative** [comment]
@matejkramny nice thank you for the quick response.
